# Generated by Django 3.1.6 on 2021-02-02 16:44

from django.db import migrations, models
import filmes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id_filme', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_lancamento', models.IntegerField()),
                ('arte', models.ImageField(blank=True, null=True, upload_to=filmes.models.upload)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
